### ISSUE TITLE
useNextCssRemovalPrevention with app router

### ISSUE THREAD

**Issue by badtant** [MadeInHaus/haus-core#148]
Hi, I would like to try useNextCssRemovalPrevention with app router.
Right now the hook uses next/router which is only for pages router. Could this be migrated to next/navigation instead which is supporter in both pages and app routers?

Thanks

**Comment by claus** [comment]
Hi @badtant, unfortunately PageTransition does not support app router based Next applications, and we do not plan to support them anytime soon.
